package View;

import Model.ff1;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class form5 extends javax.swing.JFrame {

    ArrayList<ff1> userList = new ArrayList<>();

    ///// Contructor
    public form5() {
        initComponents();
        userList = new DAO.ConnectionSQL().getListUser();
        bunk.setEnabled(false);

        // Thiết lập kích thước cho JFrame
        setSize(700, 700);
        setBackground(Color.yellow);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); // Để đóng ứng dụng khi nhấn nút đóng
        setLocationRelativeTo(null); // Để cửa sổ hiển thị ở giữa màn hình
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bun = new javax.swing.JTextField();
        chan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bon = new javax.swing.JPasswordField();
        fefe = new javax.swing.JButton();
        tu = new javax.swing.JButton();
        bunk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ff = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T COFFEE SIGN UP");
        setBackground(java.awt.Color.white);
        setSize(new java.awt.Dimension(500, 700));

        bun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Keyreleased(evt);
            }
        });

        chan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chanKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("User Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phone number:");

        bon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bonKeyReleased(evt);
            }
        });

        fefe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fefe.setText("Clear");
        fefe.setPreferredSize(new java.awt.Dimension(80, 100));
        fefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fefeActionPerformed(evt);
            }
        });

        tu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tu.setText("Login");
        tu.setPreferredSize(new java.awt.Dimension(80, 100));
        tu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuActionPerformed(evt);
            }
        });

        bunk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bunk.setText("Save");
        bunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Email:");

        ff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ffKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bon, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addComponent(chan)
                        .addComponent(ff)
                        .addComponent(bun))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fefe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(tu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bunk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5095, 5095, 5095))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bunk)
                    .addComponent(fefe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//////////////// ///////////////////////////////////////////////////////////////////////Clear button
    private void fefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fefeActionPerformed
        clear();
    }//GEN-LAST:event_fefeActionPerformed
/////////////// ////////////////////////////////////////////////////////////////////Login button
    private void tuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuActionPerformed

        new form3().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_tuActionPerformed
//save to database
    public void saVe(){
        ff1 user = new ff1();
        user.setUserName(bun.getText());
        user.setPassWord(bon.getText());
        user.setEmail(chan.getText());
        try {
            if (new DAO.ConnectionSQL().addUserToDb(user)) {
                JOptionPane.showMessageDialog(rootPane, "Save account success.");
            }
        } catch (Exception e) {
            if (new DAO.ConnectionSQL().addUserToDb(user) == false) {
                JOptionPane.showMessageDialog(rootPane, "Cannot save ! Error: " + e.toString());
            }
        }
    }
/////////////// Save button
    private void bunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunkActionPerformed
        
        checkNum();
         
    }//GEN-LAST:event_bunkActionPerformed
///////////////////// ///////////////////////////////////////////////////////KeyReleased
    private void Keyreleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keyreleased
        validateFields();

    }//GEN-LAST:event_Keyreleased

    private void bonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_bonKeyReleased

    private void chanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chanKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_chanKeyReleased

    private void ffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ffKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_ffKeyReleased
/////////////////////////////////////////////////////////////////////////////////////Clear method

    public void clear() {
        bun.setText("FFFF");
        bon.setText("FFFF");
        chan.setText("FFFF");
    }

    //////// ///////////////////////////////////////////////////////////////////////Validate - Kiem tra hop le
    public void validateFields() {
        String userName = bun.getText();
        String password = bon.getText();
        String email = chan.getText();
        String phoneNumber = ff.getText();
        String phoneParterm = "^[0-9]*$";
        String emailParterm = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
        if (!userName.equals("") && !password.equals("") && email.matches(emailParterm) && phoneNumber.matches(phoneParterm) ) {
             
            bunk.setEnabled(true);

        } else {
            bunk.setEnabled(false);
        }

    }
//check length number

    public void checkNum() {
        String phoneNumber = ff.getText();
        if (phoneNumber.length() < 10  && phoneNumber.equals("")) { 
            JOptionPane.showMessageDialog(null, "Phone number must have 10numbers !");
        } else {
           saVe();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form5().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField bon;
    private javax.swing.JTextField bun;
    private javax.swing.JButton bunk;
    private javax.swing.JTextField chan;
    private javax.swing.JButton fefe;
    private javax.swing.JTextField ff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton tu;
    // End of variables declaration//GEN-END:variables
}
